# Generated by Django 5.1.4 on 2025-03-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("core", "0001_initial"),
	]

	operations = [
		migrations.AlterField(
			model_name="marketalert",
			name="short_summary",
			field=models.CharField(max_length=200),
		),
	]
