# Generated by Django 5.1.4 on 2025-05-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_marketalert_short_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMarketAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('sentiment', models.CharField(choices=[('Bullish', 'Bullish'), ('Neutral', 'Neutral'), ('Bearish', 'Bearish')], default='Neutral', max_length=20)),
                ('sentiment_reasoning', models.TextField()),
                ('news_articles', models.JSONField(default=list)),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'News Market Alert',
                'verbose_name_plural': 'News Market Alerts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
