# Generated by Django 5.1.4 on 2025-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsmarketalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoNewsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('sentiment', models.CharField(choices=[('Bullish', 'Bullish'), ('Neutral', 'Neutral'), ('Bearish', 'Bearish')], default='Neutral', max_length=20)),
                ('sentiment_reasoning', models.TextField()),
                ('crypto_news_articles', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Crypto News Alert',
                'verbose_name_plural': 'Crypto News Alerts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='core_crypto_timesta_4b003d_idx'), models.Index(fields=['sentiment'], name='core_crypto_sentime_7c341d_idx')],
            },
        ),
    ]
