# Generated by Django 5.1.4 on 2025-07-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cryptonewsalert'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calendarmarketalert',
            name='core_calend_sent_bdba0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketscreenerresult',
            name='core_market_sent_4f1e03_idx',
        ),
        migrations.RemoveField(
            model_name='calendarmarketalert',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='marketalert',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='marketscreenerresult',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='newsmarketalert',
            name='sent',
        ),
    ]
