BELLWETHER_ASSETS = {
	"1": {
		"asset_type": "Index",
		"symbol": "^SPX",
		"name": "S&P 500 Index",
		"category": "Global Trends, U.S. Economy",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^SPX?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^SPX?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^SPX?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^SPX?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents broad U.S. equities; often positively correlated with other global equity indices (e.g., MSCI World) and negatively correlated with volatility (VIX) and safe-haven assets (Gold, USD) in risk-off scenarios.",
	},
	"2": {
		"asset_type": "Index",
		"symbol": "^IXIC",
		"name": "Nasdaq Composite",
		"category": "Tech Sector, Growth Stocks",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^IXIC?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^IXIC?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^IXIC?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^IXIC?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents U.S. technology and growth equities; often positively correlated with SPX and risk-on assets (e.g., BTC), and tends to be negatively correlated with the U.S. Dollar (DXY) in risk-on conditions.",
	},
	"3": {
		"asset_type": "Volatility",
		"symbol": "^VIX",
		"name": "VIX (Volatility Index)",
		"category": "Market Volatility",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^VIX?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^VIX?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^VIX?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^VIX?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Measures implied volatility/fear in U.S. equities; typically negatively correlated with equities (SPX) and positively correlated with safe-haven assets (Gold, USD) during periods of market stress.",
	},
	"4": {
		"asset_type": "Currency (FX)",
		"symbol": "DX-Y.NYB",
		"name": "US Dollar Index",
		"category": "Global Currency Markets",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/DX-Y.NYB?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/DX-Y.NYB?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/DX-Y.NYB?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/DX-Y.NYB?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks the U.S. Dollar strength; often negatively correlated with equities and commodities (e.g., WTI, Copper), and positively correlated with safe-haven flows in risk-off periods.",
	},
	"5": {
		"asset_type": "Currency (FX)",
		"symbol": "EURUSD",
		"name": "Euro/US Dollar",
		"category": "Major Currency Pair",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/EURUSD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/EURUSD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/EURUSD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/EURUSD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Reflects relative strength of the Eurozone vs. the U.S.; often positively correlated with European equities (EURO STOXX 50) and negatively correlated with DXY.",
	},
	"6": {
		"asset_type": "Currency (FX)",
		"symbol": "USDJPY",
		"name": "US Dollar/Japanese Yen",
		"category": "Risk Sentiment, Safe Haven",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/USDJPY?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/USDJPY?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/USDJPY?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/USDJPY?type=sma&period=200&apikey=your_api_key",
		"descriptors": "JPY is considered a safe-haven currency; in risk-off scenarios JPY tends to appreciate, causing USD/JPY to fall. Thus USD/JPY often inversely reflects global equity sentiment.",
	},
	"7": {
		"asset_type": "Commodity",
		"symbol": "WTI",
		"name": "Crude Oil",
		"category": "Economic Activity Indicator",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/WTI?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/WTI?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/WTI?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/WTI?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Reflects global growth and energy demand; often positively correlated with equities (SPX) and negatively correlated with USD (DXY).",
	},
	"8": {
		"asset_type": "Commodity",
		"symbol": "GLD",
		"name": "Gold",
		"category": "Safe-Haven Asset",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/GLD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/GLD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/GLD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/GLD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Viewed as a store of value; often positively correlated with volatility (VIX) and negatively correlated with USD (DXY) and equities (SPX) during risk-off scenarios.",
	},
	"9": {
		"asset_type": "Index",
		"symbol": "^RUT",
		"name": "Russell 2000",
		"category": "Small-Cap Stocks",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^RUT?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^RUT?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^RUT?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^RUT?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents U.S. small-cap equities; generally positively correlated with broader U.S. equities (SPX) and negatively correlated with VIX and safe-haven assets.",
	},
	"10": {
		"asset_type": "Index",
		"symbol": "MSCIWORLD",
		"name": "MSCI World Index",
		"category": "Global Equity Performance",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/MSCIWORLD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/MSCIWORLD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/MSCIWORLD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/MSCIWORLD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents developed market equities; often positively correlated with SPX and other major indices, and negatively correlated with safe-haven assets (Gold, VIX).",
	},
	"11": {
		"asset_type": "Cryptocurrency",
		"symbol": "BTCUSD",
		"name": "Bitcoin",
		"category": "Digital Asset Sentiment",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/BTCUSD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/BTCUSD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/BTCUSD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/BTCUSD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Leading cryptocurrency; correlations vary, but has often been positively correlated with risk-on assets (e.g., NASDAQ) and negatively correlated with safe-haven assets in recent risk-on periods.",
	},
	"12": {
		"asset_type": "Cryptocurrency",
		"symbol": "ETHUSD",
		"name": "Ethereum",
		"category": "Crypto Market Sentiment",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/ETHUSD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/ETHUSD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/ETHUSD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/ETHUSD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Major crypto asset correlated with BTC; tends to have a positive correlation with other digital assets and risk-on sentiment, with less correlation to traditional safe-havens.",
	},
	"13": {
		"asset_type": "Index",
		"symbol": "000001.SS",
		"name": "Shanghai Composite",
		"category": "Chinese Economic Indicator",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/000001.SS?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/000001.SS?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/000001.SS?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/000001.SS?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents China's equity market; often positively correlated with other emerging markets (MSCI EM) and negatively correlated with a strong USD (DXY).",
	},
	"14": {
		"asset_type": "Fixed Income",
		"symbol": "^TNX",
		"name": "10-Year Treasury Yield",
		"category": "Bond Market Indicator",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^TNX?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^TNX?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^TNX?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^TNX?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Reflects long-term U.S. interest rate expectations; often negatively correlated with equities (SPX) during tightening cycles and negatively correlated with Gold when yields rise.",
	},
	"15": {
		"asset_type": "Index",
		"symbol": "^DJI",
		"name": "Dow Jones Industrial Avg.",
		"category": "U.S. Large-Cap Stocks",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^DJI?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^DJI?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^DJI?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^DJI?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents blue-chip U.S. equities; positively correlated with SPX and MSCI World, and negatively correlated with VIX and safe-haven flows.",
	},
	"16": {
		"asset_type": "Index",
		"symbol": "^N225",
		"name": "Nikkei 225",
		"category": "Japanese Stock Market",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^N225?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^N225?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^N225?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^N225?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Reflects Japanese equities; often positively correlated with global equities (MSCI World) and inversely related to JPY\u2019s safe-haven strength, so negatively correlated with USD/JPY movements in risk-off scenarios.",
	},
	"17": {
		"asset_type": "Commodity",
		"symbol": "XAGUSD",
		"name": "Silver",
		"category": "Precious Metal",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/XAGUSD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XAGUSD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XAGUSD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XAGUSD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Has both monetary and industrial uses; often positively correlated with Gold and negatively correlated with USD (DXY).",
	},
	"18": {
		"asset_type": "Currency (FX)",
		"symbol": "GBPUSD",
		"name": "British Pound/US Dollar",
		"category": "Major Currency Pair",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/GBPUSD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/GBPUSD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/GBPUSD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/GBPUSD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Reflects UK vs. U.S. economic conditions; often positively correlated with UK equities (FTSE 100) and negatively correlated with USD (DXY).",
	},
	"19": {
		"asset_type": "Commodity",
		"symbol": "NG",
		"name": "Natural Gas",
		"category": "Energy Market Indicator",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/NG?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/NG?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/NG?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/NG?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Reflects energy demand and sometimes weather patterns; tends to be positively correlated with other energy commodities (Oil) and negatively correlated with USD (DXY).",
	},
	"20": {
		"asset_type": "Index",
		"symbol": "^FTSE",
		"name": "FTSE 100",
		"category": "UK Stock Market",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^FTSE?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^FTSE?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^FTSE?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^FTSE?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents UK equities; often positively correlated with European equities (STOXX 50) and negatively correlated with safe-haven flows (strong USD).",
	},
	"21": {
		"asset_type": "Index",
		"symbol": "^HSI",
		"name": "Hang Seng Index",
		"category": "Hong Kong Stock Market",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^HSI?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^HSI?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^HSI?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^HSI?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents Hong Kong and China-related equities; often positively correlated with Asian and emerging markets (MSCI EM) and negatively correlated with USD strength.",
	},
	"22": {
		"asset_type": "Fixed Income",
		"symbol": "^FVX",
		"name": "5-Year Treasury Yield",
		"category": "Bond Market Indicator",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^FVX?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^FVX?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^FVX?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^FVX?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Reflects intermediate U.S. interest rate expectations; often negatively correlated with equities (SPX) when rates rise sharply and negatively correlated with Gold when real yields increase.",
	},
	"23": {
		"asset_type": "Cryptocurrency",
		"symbol": "XRPUSD",
		"name": "Ripple",
		"category": "Crypto Market Sentiment",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/XRPUSD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XRPUSD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XRPUSD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XRPUSD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "A digital asset primarily for cross-border payments; often positively correlated with the broader crypto market (BTC, ETH).",
	},
	"24": {
		"asset_type": "Fixed Income",
		"symbol": "^TYX",
		"name": "30-Year Treasury Yield",
		"category": "Long-Term Bond Indicator",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^TYX?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^TYX?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^TYX?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^TYX?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Reflects long-term U.S. rate/inflation views; often negatively correlated with equities (SPX) when yields spike, and negatively correlated with Gold in a rising rate environment.",
	},
	"25": {
		"asset_type": "Index",
		"symbol": "^BSESN",
		"name": "BSE Sensex",
		"category": "Indian Stock Market",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^BSESN?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^BSESN?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^BSESN?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^BSESN?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents Indian equities; often positively correlated with other emerging markets (MSCI EM) and negatively correlated with strong USD (DXY).",
	},
	"26": {
		"asset_type": "Index",
		"symbol": "^STOXX50E",
		"name": "EURO STOXX 50",
		"category": "European Stocks",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^STOXX50E?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^STOXX50E?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^STOXX50E?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^STOXX50E?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents large-cap European equities; positively correlated with EUR/USD and global equities, negatively correlated with safe-haven flows.",
	},
	"27": {
		"asset_type": "Index",
		"symbol": "^AORD",
		"name": "ASX 200",
		"category": "Australian Stock Market",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^AORD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^AORD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^AORD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^AORD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents Australian equities; often positively correlated with global equities and commodity prices, and negatively correlated with strong USD.",
	},
	"28": {
		"asset_type": "Fixed Income",
		"symbol": "^IRX",
		"name": "3-Month Treasury Yield",
		"category": "Short-Term Bond Indicator",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^IRX?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^IRX?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^IRX?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^IRX?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Reflects short-term U.S. interest rate conditions; often negatively correlated with equities (SPX) in tightening cycles and positively correlated with USD.",
	},
	"29": {
		"asset_type": "Cryptocurrency",
		"symbol": "SOLUSD",
		"name": "Solana",
		"category": "Crypto Market Sentiment",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/SOLUSD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/SOLUSD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/SOLUSD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/SOLUSD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "High-speed blockchain token; positively correlated with the broader crypto market (BTC, ETH).",
	},
	"30": {
		"asset_type": "Index",
		"symbol": "^IBEX",
		"name": "IBEX 35",
		"category": "Spanish Stock Market",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^IBEX?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^IBEX?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^IBEX?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^IBEX?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents Spanish equities; positively correlated with European equities (STOXX 50) and EUR strength, negatively correlated with safe-haven flows.",
	},
	"31": {
		"asset_type": "ETF",
		"symbol": "EEM",
		"name": "Emerging Markets ETF",
		"category": "ETF",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/EEM?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/EEM?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/EEM?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/EEM?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Reflects global risk sentiment; highly sensitive to global growth and dollar strength, representing diverse emerging markets.",
	},
	"32": {
		"asset_type": "Currency (FX)",
		"symbol": "USDBRL",
		"name": "Brazilian Real",
		"category": "Currency (FX)",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/USDBRL?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/USDBRL?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/USDBRL?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/USDBRL?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks sentiment in emerging markets, commodity economies, and FX volatility; negatively correlated with global risk-on sentiment.",
	},
	"33": {
		"asset_type": "Commodity",
		"symbol": "BZUSD\n",
		"name": "Brent Crude Oil",
		"category": "Global Oil Price",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/BZUSD\n?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/BZUSD\n?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/BZUSD\n?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/BZUSD\n?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Major global oil benchmark; positively correlated with risk assets and global growth, negatively correlated with USD.",
	},
	"34": {
		"asset_type": "Index",
		"symbol": "^OSEAX",
		"name": "Oslo All-Share Index",
		"category": "Norwegian Stock Market",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^OSEAX?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^OSEAX?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^OSEAX?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^OSEAX?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Reflects Norway\u2019s equities; positively correlated with Oil (Brent) and European equities, negatively correlated with USD strength.",
	},
	"35": {
		"asset_type": "Index",
		"symbol": "^J20X.JO",
		"name": "FTSE/JSE All-Share",
		"category": "South African Stock Market",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^J20X.JO?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^J20X.JO?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^J20X.JO?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^J20X.JO?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents South African equities; positively correlated with global risk sentiment and Gold (as SA is a major producer), negatively correlated with USD/ZAR strength.",
	},
	"36": {
		"asset_type": "Commodity",
		"symbol": "LBUSD",
		"name": "Lumber Futures",
		"category": "Housing and Construction Proxy",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/LBUSD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/LBUSD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/LBUSD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/LBUSD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Reflects housing demand and economic cycles, especially in North America.",
	},
	"37": {
		"asset_type": "ETF",
		"symbol": "ICLN",
		"name": "iShares Global Clean Energy ETF",
		"category": "Environmental Policy Proxy",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/ICLN?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/ICLN?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/ICLN?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/ICLN?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks global clean energy equities; often positively correlated with risk-on sentiment and global growth themes, and negatively correlated with safe-haven assets like USD (DXY) and Treasury bonds.",
	},
	"38": {
		"asset_type": "ETF",
		"symbol": "^IXIC",
		"name": "Nasdaq Composite",
		"category": "Tech Sector, Growth Stocks",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/^IXIC?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^IXIC?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^IXIC?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/^IXIC?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents U.S. technology and growth equities; positively correlated with risk-on assets and negatively correlated with the U.S. Dollar (DXY) in risk-on conditions.",
	},
	"39": {
		"asset_type": "ETF",
		"symbol": "QQQ",
		"name": "Invesco QQQ Trust",
		"category": "U.S. Technology Stocks",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/QQQ?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/QQQ?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/QQQ?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/QQQ?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks Nasdaq-100 Index, focusing on tech and growth stocks; highly sensitive to risk-on sentiment and interest rate trends.",
	},
	"40": {
		"asset_type": "ETF",
		"symbol": "GLD",
		"name": "SPDR Gold Shares",
		"category": "Safe-Haven Asset",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/GLD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/GLD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/GLD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/GLD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks gold prices; often positively correlated with volatility (VIX) and negatively correlated with USD (DXY) and equities in risk-off scenarios.",
	},
	"41": {
		"asset_type": "ETF",
		"symbol": "ACWI",
		"name": "iShares MSCI ACWI ETF",
		"category": "Global Equity Trends",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/ACWI?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/ACWI?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/ACWI?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/ACWI?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks global equities across developed and emerging markets; a broad indicator of global risk sentiment.",
	},
	"42": {
		"asset_type": "ETF",
		"symbol": "IWM",
		"name": "iShares Russell 2000 ETF",
		"category": "U.S. Small-Cap Stocks",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/IWM?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/IWM?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/IWM?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/IWM?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks U.S. small-cap stocks, reflecting domestic risk sentiment and economic growth expectations.",
	},
	"43": {
		"asset_type": "ETF",
		"symbol": "HGUSD",
		"name": "Copper Futures",
		"category": "Industrial Commodity",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/HGUSD?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/HGUSD?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/HGUSD?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/HGUSD?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks global industrial demand; often positively correlated with equities and global growth, making it a strong risk-on indicator.",
	},
	"44": {
		"asset_type": "Stock",
		"symbol": "XLV",
		"name": "Health Care Select Sector SPDR Fund",
		"category": "U.S. Healthcare Sector ETF",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/XLV?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XLV?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XLV?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XLV?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks U.S. healthcare equities; often considered a defensive sector and can perform well in bearish or uncertain economic conditions.",
	},
	"45": {
		"asset_type": "ETF",
		"symbol": "EWZ",
		"name": "iShares MSCI Brazil ETF",
		"category": "Emerging Markets ETF",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/EWZ?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/EWZ?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/EWZ?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/EWZ?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks Brazilian equities; sensitive to commodity prices and global risk sentiment, representing a key emerging market economy.",
	},
	"46": {
		"asset_type": "ETF",
		"symbol": "XLF",
		"name": "Financial Select Sector ETF",
		"category": "U.S. Financial Sector ETF",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/XLF?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XLF?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XLF?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XLF?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Represents U.S. financial equities, which are sensitive to interest rate trends and economic cycles, making it a good indicator for risk-on/off sentiment.",
	},
	"47": {
		"asset_type": "ETF",
		"symbol": "EWY",
		"name": "iShares MSCI South Korea ETF",
		"category": "Emerging Markets ETF",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/EWY?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/EWY?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/EWY?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/EWY?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks South Korean equities; a key proxy for global trade and tech demand, often reflecting shifts in global risk sentiment.",
	},
	"48": {
		"asset_type": "ETF",
		"symbol": "IGOV",
		"name": "iShares International Treasury Bond ETF",
		"category": "Global Fixed Income",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/IGOV?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/IGOV?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/IGOV?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/IGOV?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks international government bonds, offering exposure to global fixed-income markets outside the U.S.",
	},
	"49": {
		"asset_type": "ETF",
		"symbol": "VNQ",
		"name": "Vanguard Real Estate ETF",
		"category": "Real Estate",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/VNQ?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/VNQ?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/VNQ?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/VNQ?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Provides exposure to U.S. real estate equities, reflecting housing and commercial property trends.",
	},
	"50": {
		"asset_type": "ETF",
		"symbol": "TIP",
		"name": "iShares TIPS Bond ETF",
		"category": "Inflation-Linked Bonds",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/TIP?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/TIP?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/TIP?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/TIP?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks U.S. Treasury Inflation-Protected Securities (TIPS), providing exposure to inflation-adjusted bonds.",
	},
	"51": {
		"asset_type": "ETF",
		"symbol": "XLK",
		"name": "Technology Select Sector SPDR Fund",
		"category": "U.S. Technology Sector",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/XLK?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XLK?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XLK?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/XLK?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Focuses on U.S. technology equities, including major tech companies, making it highly correlated with risk-on sentiment and innovation trends.",
	},
	"52": {
		"asset_type": "ETF",
		"symbol": "DBC",
		"name": "Invesco DB Commodity Index Fund",
		"category": "Broad Commodities",
		"api_type": 1,
		"RSI": "https://financialmodelingprep.com/api/v3/technical_indicator/2hour/DBC?type=rsi&period=28&apikey=your_api_key",
		"EMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/DBC?type=ema&period=50&apikey=your_api_key",
		"DEMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/DBC?type=dema&period=20&apikey=your_api_key",
		"SMA": "https://financialmodelingprep.com/api/v3/technical_indicator/4hour/DBC?type=sma&period=200&apikey=your_api_key",
		"descriptors": "Tracks a diversified basket of commodities, including energy, agriculture, and metals, providing a broad inflation hedge and economic insight.",
	},
}
