COUNTRY_DATA = {
	# North America
	"US": {
		"name": "United States",
		"tier": 1,
		"score": 4.0,
		"flag": "https://flagcdn.com/us.svg",
	},
	"CA": {
		"name": "Canada",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/ca.svg",
	},
	"MX": {
		"name": "Mexico",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/mx.svg",
	},
	"CR": {
		"name": "Costa Rica",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/cr.svg",
	},
	"CU": {
		"name": "Cuba",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/cu.svg",
	},
	"DO": {
		"name": "Dominican Republic",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/do.svg",
	},
	"SV": {
		"name": "El Salvador",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/sv.svg",
	},
	"GT": {
		"name": "Guatemala",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/gt.svg",
	},
	"HT": {
		"name": "Haiti",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ht.svg",
	},
	"HN": {
		"name": "Honduras",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/hn.svg",
	},
	"JM": {
		"name": "Jamaica",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/jm.svg",
	},
	"NI": {
		"name": "Nicaragua",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ni.svg",
	},
	"PA": {
		"name": "Panama",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/pa.svg",
	},
	"TT": {
		"name": "Trinidad and Tobago",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/tt.svg",
	},
	"BS": {
		"name": "Bahamas",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bs.svg",
	},
	"BB": {
		"name": "Barbados",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bb.svg",
	},
	"BZ": {
		"name": "Belize",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bz.svg",
	},
	"GD": {
		"name": "Grenada",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/gd.svg",
	},
	"LC": {
		"name": "Saint Lucia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/lc.svg",
	},
	"VC": {
		"name": "Saint Vincent and the Grenadines",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/vc.svg",
	},
	"AG": {
		"name": "Antigua and Barbuda",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ag.svg",
	},
	"DM": {
		"name": "Dominica",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/dm.svg",
	},
	"KN": {
		"name": "Saint Kitts and Nevis",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/kn.svg",
	},
	# South America
	"BR": {
		"name": "Brazil",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/br.svg",
	},
	"AR": {
		"name": "Argentina",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ar.svg",
	},
	"CL": {
		"name": "Chile",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/cl.svg",
	},
	"CO": {
		"name": "Colombia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/co.svg",
	},
	"PE": {
		"name": "Peru",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/pe.svg",
	},
	"VE": {
		"name": "Venezuela",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ve.svg",
	},
	"EC": {
		"name": "Ecuador",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ec.svg",
	},
	"BO": {
		"name": "Bolivia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bo.svg",
	},
	"PY": {
		"name": "Paraguay",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/py.svg",
	},
	"UY": {
		"name": "Uruguay",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/uy.svg",
	},
	"GY": {
		"name": "Guyana",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/gy.svg",
	},
	"SR": {
		"name": "Suriname",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/sr.svg",
	},
	# Europe
	"EU": {
		"name": "European Union",
		"tier": 1,
		"score": 4.0,
		"flag": "https://flagcdn.com/eu.svg",
	},
	"UK": {
		"name": "United Kingdom",
		"tier": 1,
		"score": 4.0,
		"flag": "https://flagcdn.com/gb.svg",
	},
	"DE": {
		"name": "Germany",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/de.svg",
	},
	"FR": {
		"name": "France",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/fr.svg",
	},
	"IT": {
		"name": "Italy",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/it.svg",
	},
	"ES": {
		"name": "Spain",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/es.svg",
	},
	"NL": {
		"name": "Netherlands",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/nl.svg",
	},
	"CH": {
		"name": "Switzerland",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/ch.svg",
	},
	"RU": {
		"name": "Russia",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/ru.svg",
	},
	"SE": {
		"name": "Sweden",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/se.svg",
	},
	"NO": {
		"name": "Norway",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/no.svg",
	},
	"DK": {
		"name": "Denmark",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/dk.svg",
	},
	"IE": {
		"name": "Ireland",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/ie.svg",
	},
	"BE": {
		"name": "Belgium",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/be.svg",
	},
	"AT": {
		"name": "Austria",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/at.svg",
	},
	"FI": {
		"name": "Finland",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/fi.svg",
	},
	"PL": {
		"name": "Poland",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/pl.svg",
	},
	"PT": {
		"name": "Portugal",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/pt.svg",
	},
	"GR": {
		"name": "Greece",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/gr.svg",
	},
	"CZ": {
		"name": "Czech Republic",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/cz.svg",
	},
	"RO": {
		"name": "Romania",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ro.svg",
	},
	"HU": {
		"name": "Hungary",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/hu.svg",
	},
	"SK": {
		"name": "Slovakia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/sk.svg",
	},
	"LU": {
		"name": "Luxembourg",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/lu.svg",
	},
	"BG": {
		"name": "Bulgaria",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bg.svg",
	},
	"HR": {
		"name": "Croatia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/hr.svg",
	},
	"SI": {
		"name": "Slovenia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/si.svg",
	},
	"LT": {
		"name": "Lithuania",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/lt.svg",
	},
	"LV": {
		"name": "Latvia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/lv.svg",
	},
	"EE": {
		"name": "Estonia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ee.svg",
	},
	"CY": {
		"name": "Cyprus",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/cy.svg",
	},
	"MT": {
		"name": "Malta",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/mt.svg",
	},
	"IS": {
		"name": "Iceland",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/is.svg",
	},
	"AL": {
		"name": "Albania",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/al.svg",
	},
	"MD": {
		"name": "Moldova",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/md.svg",
	},
	"MK": {
		"name": "North Macedonia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/mk.svg",
	},
	"ME": {
		"name": "Montenegro",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/me.svg",
	},
	"RS": {
		"name": "Serbia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/rs.svg",
	},
	"BA": {
		"name": "Bosnia and Herzegovina",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ba.svg",
	},
	# Asia
	"CN": {
		"name": "China",
		"tier": 1,
		"score": 4.0,
		"flag": "https://flagcdn.com/cn.svg",
	},
	"JP": {
		"name": "Japan",
		"tier": 1,
		"score": 4.0,
		"flag": "https://flagcdn.com/jp.svg",
	},
	"IN": {
		"name": "India",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/in.svg",
	},
	"KR": {
		"name": "South Korea",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/kr.svg",
	},
	"HK": {
		"name": "Hong Kong SAR",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/hk.svg",
	},
	"SG": {
		"name": "Singapore",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/sg.svg",
	},
	"ID": {
		"name": "Indonesia",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/id.svg",
	},
	"TH": {
		"name": "Thailand",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/th.svg",
	},
	"MY": {
		"name": "Malaysia",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/my.svg",
	},
	"PH": {
		"name": "Philippines",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/ph.svg",
	},
	"VN": {
		"name": "Vietnam",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/vn.svg",
	},
	"TW": {
		"name": "Taiwan",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/tw.svg",
	},
	"PK": {
		"name": "Pakistan",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/pk.svg",
	},
	"BD": {
		"name": "Bangladesh",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bd.svg",
	},
	"LK": {
		"name": "Sri Lanka",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/lk.svg",
	},
	"NP": {
		"name": "Nepal",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/np.svg",
	},
	"MM": {
		"name": "Myanmar",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/mm.svg",
	},
	"KH": {
		"name": "Cambodia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/kh.svg",
	},
	"LA": {
		"name": "Laos",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/la.svg",
	},
	"MN": {
		"name": "Mongolia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/mn.svg",
	},
	"BN": {
		"name": "Brunei",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bn.svg",
	},
	"BT": {
		"name": "Bhutan",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bt.svg",
	},
	"MV": {
		"name": "Maldives",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/mv.svg",
	},
	"TL": {
		"name": "Timor-Leste",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/tl.svg",
	},
	# Middle East
	"SA": {
		"name": "Saudi Arabia",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/sa.svg",
	},
	"AE": {
		"name": "United Arab Emirates",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/ae.svg",
	},
	"IL": {
		"name": "Israel",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/il.svg",
	},
	"TR": {
		"name": "Turkey",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/tr.svg",
	},
	"IR": {
		"name": "Iran",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ir.svg",
	},
	"QA": {
		"name": "Qatar",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/qa.svg",
	},
	"KW": {
		"name": "Kuwait",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/kw.svg",
	},
	"BH": {
		"name": "Bahrain",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bh.svg",
	},
	"OM": {
		"name": "Oman",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/om.svg",
	},
	"JO": {
		"name": "Jordan",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/jo.svg",
	},
	"LB": {
		"name": "Lebanon",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/lb.svg",
	},
	"IQ": {
		"name": "Iraq",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/iq.svg",
	},
	"SY": {
		"name": "Syria",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/sy.svg",
	},
	"YE": {
		"name": "Yemen",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ye.svg",
	},
	# Africa
	"ZA": {
		"name": "South Africa",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/za.svg",
	},
	"NG": {
		"name": "Nigeria",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ng.svg",
	},
	"EG": {
		"name": "Egypt",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/eg.svg",
	},
	"MA": {
		"name": "Morocco",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ma.svg",
	},
	"KE": {
		"name": "Kenya",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ke.svg",
	},
	"GH": {
		"name": "Ghana",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/gh.svg",
	},
	"ET": {
		"name": "Ethiopia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/et.svg",
	},
	"TZ": {
		"name": "Tanzania",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/tz.svg",
	},
	"UG": {
		"name": "Uganda",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ug.svg",
	},
	"DZ": {
		"name": "Algeria",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/dz.svg",
	},
	"AO": {
		"name": "Angola",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ao.svg",
	},
	"TN": {
		"name": "Tunisia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/tn.svg",
	},
	"LY": {
		"name": "Libya",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ly.svg",
	},
	"SD": {
		"name": "Sudan",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/sd.svg",
	},
	"CI": {
		"name": "Côte d'Ivoire",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ci.svg",
	},
	"CM": {
		"name": "Cameroon",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/cm.svg",
	},
	"CD": {
		"name": "DR Congo",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/cd.svg",
	},
	"SN": {
		"name": "Senegal",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/sn.svg",
	},
	"ZW": {
		"name": "Zimbabwe",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/zw.svg",
	},
	"ZM": {
		"name": "Zambia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/zm.svg",
	},
	"BW": {
		"name": "Botswana",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bw.svg",
	},
	"MU": {
		"name": "Mauritius",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/mu.svg",
	},
	"MZ": {
		"name": "Mozambique",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/mz.svg",
	},
	"NA": {
		"name": "Namibia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/na.svg",
	},
	"RW": {
		"name": "Rwanda",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/rw.svg",
	},
	"GA": {
		"name": "Gabon",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ga.svg",
	},
	"MG": {
		"name": "Madagascar",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/mg.svg",
	},
	"MW": {
		"name": "Malawi",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/mw.svg",
	},
	"ML": {
		"name": "Mali",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ml.svg",
	},
	"BF": {
		"name": "Burkina Faso",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bf.svg",
	},
	"NE": {
		"name": "Niger",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ne.svg",
	},
	"TD": {
		"name": "Chad",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/td.svg",
	},
	"SO": {
		"name": "Somalia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/so.svg",
	},
	"ER": {
		"name": "Eritrea",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/er.svg",
	},
	"BI": {
		"name": "Burundi",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bi.svg",
	},
	"SL": {
		"name": "Sierra Leone",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/sl.svg",
	},
	"LR": {
		"name": "Liberia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/lr.svg",
	},
	"CF": {
		"name": "Central African Republic",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/cf.svg",
	},
	"CG": {
		"name": "Republic of the Congo",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/cg.svg",
	},
	"TG": {
		"name": "Togo",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/tg.svg",
	},
	"MR": {
		"name": "Mauritania",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/mr.svg",
	},
	"SZ": {
		"name": "Eswatini",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/sz.svg",
	},
	"DJ": {
		"name": "Djibouti",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/dj.svg",
	},
	"LS": {
		"name": "Lesotho",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ls.svg",
	},
	"GN": {
		"name": "Guinea",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/gn.svg",
	},
	"GW": {
		"name": "Guinea-Bissau",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/gw.svg",
	},
	"GM": {
		"name": "Gambia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/gm.svg",
	},
	"BJ": {
		"name": "Benin",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/bj.svg",
	},
	"KM": {
		"name": "Comoros",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/km.svg",
	},
	"CV": {
		"name": "Cape Verde",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/cv.svg",
	},
	"ST": {
		"name": "São Tomé and Príncipe",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/st.svg",
	},
	"SC": {
		"name": "Seychelles",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/sc.svg",
	},
	"SS": {
		"name": "South Sudan",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ss.svg",
	},
	# Oceania
	"AU": {
		"name": "Australia",
		"tier": 2,
		"score": 3.0,
		"flag": "https://flagcdn.com/au.svg",
	},
	"NZ": {
		"name": "New Zealand",
		"tier": 3,
		"score": 2.0,
		"flag": "https://flagcdn.com/nz.svg",
	},
	"PG": {
		"name": "Papua New Guinea",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/pg.svg",
	},
	"FJ": {
		"name": "Fiji",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/fj.svg",
	},
	"SB": {
		"name": "Solomon Islands",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/sb.svg",
	},
	"VU": {
		"name": "Vanuatu",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/vu.svg",
	},
	"WS": {
		"name": "Samoa",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ws.svg",
	},
	"TO": {
		"name": "Tonga",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/to.svg",
	},
	"FM": {
		"name": "Micronesia",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/fm.svg",
	},
	"KI": {
		"name": "Kiribati",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/ki.svg",
	},
	"MH": {
		"name": "Marshall Islands",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/mh.svg",
	},
	"PW": {
		"name": "Palau",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/pw.svg",
	},
	"TV": {
		"name": "Tuvalu",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/tv.svg",
	},
	"NR": {
		"name": "Nauru",
		"tier": 4,
		"score": 1.0,
		"flag": "https://flagcdn.com/nr.svg",
	},
}
